name: Build APK

on:
  push:
    branches:
      - master
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev \
            libssl-dev cmake ninja-build \
            ccache patch

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip==23.2.1
          
          pip install cython==0.29.36
          pip install buildozer==1.5.0
          pip install sh==1.14.3

      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools

          cd $HOME/android-sdk/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          unzip commandlinetools-linux-11076708_latest.zip

          mv cmdline-tools latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses

          sdkmanager \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0"

          mkdir -p $HOME/android-sdk/tools/bin

          ln -s \
            $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            $HOME/android-sdk/tools/bin/sdkmanager

      - name: Clean previous builds
        run: |
          rm -rf .buildozer
          rm -rf ~/.buildozer

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk